### ISSUE TITLE
bug(expense): Expense is created with the wrong first due date.

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#1170]
If I create an expense on October 31st, and set it to be due next on December 1st. When it is created it has a next due of November 1st.

![image](https://user-images.githubusercontent.com/37967690/199060006-1855ecdc-badf-4a81-8e9f-f593f6c0656e.png)

![image](https://user-images.githubusercontent.com/37967690/199060093-bdfcb272-975e-4d2e-b673-09c7627e1cbe.png)

**Comment by MundhadHarsh** [comment]
I would like to work on this, can you assign it to me

**Comment by elliotcourant** [comment]
Note: This is going to be an issue with the backend. When the expense is created we should only evaluate the "next" recurrence if the next recurrence is not provided, or if it is in the past.

**Comment by elliotcourant** [comment]
https://github.com/monetr/monetr/blob/62fa273864cb338e38bf4f7c66078999ae5f8cd6/pkg/controller/spending.go#L129-L132 Specifically the issue is here, we only want to call `After` if there is not already a next recurrence defined.
