### ISSUE TITLE
bug(ui): Don't allow a goal to be created until a funding schedule is selected.

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#1171]
Right now it is possible to try to create a goal before a funding schedule has been selected. This will result in an error:

![image](https://user-images.githubusercontent.com/37967690/199061512-1509bf6f-495e-4358-960e-2194690ef251.png)

**Comment by ShivamGarg2910** [comment]
@elliotcourant , please assign me

**Comment by elliotcourant** [comment]
@ShivamGarg2910 let me know if you have any questions, I'm happy to answer anything here or in Discord. Whichever is easiest!
