### ISSUE TITLE
bug(ui): Terms of use and privacy policy links on sign up page should change on focus.

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#1196]
Right now if you tab through the elements on the sign up page, the terms of use and privacy policy links do not change their appearance when they are focused. They should show the same as if they were being hovered.

![image](https://user-images.githubusercontent.com/37967690/199872902-2bedf5a8-bf9c-473e-a2ce-a91cbc14fe4a.png)

![image](https://user-images.githubusercontent.com/37967690/199872926-335b07b5-6397-4cf4-b9cb-80e88d49d553.png)

**Comment by shubhay09** [comment]
i can fix this. give me the code and setup to fix this

**Comment by shubhay09** [comment]
i have solved it with little bit of improvement

**Comment by elliotcourant** [comment]
Being addressed in https://github.com/monetr/monetr/pull/1197
