### ISSUE TITLE
bug(ui): React query client not stable

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#1841]
https://github.com/monetr/monetr/blob/ce6ba51bc57bb5631fbf5f817b72f27dc037f96d/interface/src/components/MQueryClient.tsx#L11-L31

https://tanstack.com/query/latest/docs/eslint/stable-query-client

The query client should be declared as a useState or should be declared outside the component so that re-rendering does not recreate the query client.

**Comment by Er-Sadiq** [comment]
Hi , I think  queryClient should be placed by Memo hook , I have been Working on it ,I ll raise a PR soon

**Comment by Er-Sadiq** [comment]
Thank you, @elliotcourant  and team, for reviewing and merging the PR.
Feel free to reach out if any further adjustments are needed
Best,
Sadiq Ahmed Killedar
