### ISSUE TITLE
bug: Sign up error is not presented if there was an issue like a timeout.

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#245]
https://github.com/monetr/monetr/blob/adb3294056b6e8def3cb62aca5ba555143f88841/ui/views/Authentication/SignUpView.tsx#L191-L199

If the client experiences an issue like a gateway timeout or some other internet problem; then no error is presented to the client. Instead the page state just "unloads" with nothing helpful.

Add a generic error toast with some information from the `error` object; or add an "unknown error occurred message"

**Comment by NguyenLyy** [comment]
I want to do it. Can you guide me!

**Comment by elliotcourant** [comment]
Yes, I will post some more details on an easy way to approach this later today!

**Comment by elliotcourant** [comment]
I'd also ask that you remove the `throw error;` since we would have handling for the error at that point. Throws should be reserved for errors that we are not handling, to encourage us to handle them.

**Comment by elliotcourant** [comment]
https://github.com/monetr/monetr/pull/334 This was resolved as part of this PR.
